const wordData = [
{ word: "春節", meaning: "Spring Festival; Lunar New Year", example: "春節的時候，我們全家一起吃年夜飯。(During the Spring Festival, our whole family eats New Year’s Eve dinner together.)" },
{ word: "要求", meaning: "requirement; request; demand", example: "這個作業的要求是寫一篇三百字的文章。(The requirement for this assignment is to write a 300-character composition.)" },
{ word: "修改", meaning: "to revise; to correct; to edit", example: "老師幫我修改作文，讓內容更清楚。(The teacher helped me revise my composition to make the content clearer.)" },
{ word: "完成", meaning: "to finish; to complete", example: "我晚上十點前就完成作業了。(I finished my homework before ten at night.)" },
{ word: "寒假", meaning: "winter vacation", example: "寒假我們打算回老家過年。(During winter vacation, we plan to go back to our hometown for the New Year.)" },
{ word: "過年", meaning: "to celebrate the Chinese New Year/ Lunar New Year", example: "很多在外地工作的人都會回家過年。(Many people who work away from home go back home to celebrate the New Year.)" },
{ word: "從來", meaning: "ever; (often with 不/沒) never", example: "我從來沒看過這麼熱鬧的夜市。(I have never seen such a lively night market.)" },
{ word: "除夕", meaning: "Lunar New Year’s Eve", example: "除夕晚上我們一家人一起守歲看電視。(On New Year’s Eve our family stays up together and watches TV.)" },
{ word: "接著", meaning: "then; next; after that", example: "吃完年夜飯，接著我們一起去看煙火。(After finishing New Year’s Eve dinner, we then go watch the fireworks together.)" },
{ word: "爺爺", meaning: "grandfather (father’s father)", example: "爺爺每天早上帶我去公園散步。(Grandpa takes me to the park for a walk every morning.)" },
{ word: "奶奶", meaning: "grandmother (father’s mother)", example: "奶奶做的菜最好吃。(Grandma’s cooking is the best.)" },
{ word: "拜拜", meaning: "to pray; to worship", example: "過年時，我們一早就去廟裡拜拜。(At New Year, we go to the temple early in the morning to pray.)" },
{ word: "拜", meaning: "to pray; to worship", example: "我們在桌前拜祖先，謝謝他們的保佑。(We worship our ancestors in front of the table and thank them for their protection.)" },
{ word: "祖先", meaning: "ancestors", example: "過年時，家人一起拜祖先，表示感謝。(During the New Year, the family worships the ancestors together to show gratitude.)" },
{ word: "聚", meaning: "to gather; to get together", example: "過年的時候，親戚都聚在一起吃飯。(During the New Year, relatives all gather together to eat.)" },
{ word: "煮", meaning: "to cook; to boil", example: "今天晚上我要煮一大鍋水餃。(Tonight I’m going to cook a big pot of dumplings.)" },
{ word: "水餃", meaning: "dumplings", example: "過年的時候，我們常常全家一起包水餃。(During the New Year, our whole family often makes dumplings together.)" },
{ word: "炒", meaning: "to stir-fry", example: "媽媽在廚房炒青菜和肉片。(Mom is in the kitchen stir-frying vegetables and sliced meat.)" },
{ word: "米粉", meaning: "rice noodles", example: "我最喜歡吃媽媽煮的米粉。(I like the rice vermicelli my mom cooks the most.)" },
{ word: "煎", meaning: "to fry; to pan-fry", example: "早餐我想吃煎蛋和煎蘿蔔糕。(For breakfast I want to eat fried eggs and pan-fried radish cake.)" },
{ word: "蘿蔔", meaning: "radish", example: "桌上有一大盤切好的蘿蔔。(There is a big plate of sliced radishes on the table.)" },
{ word: "等等", meaning: "etc.; and so on", example: "桌上有蘋果、橘子、葡萄等等。(There are apples, oranges, grapes, etc. on the table.)" },
{ word: "發財", meaning: "to get rich; to make a fortune", example: "過年大家互相說「恭喜發財」。(During the New Year, everyone says “Gongxi facai” to wish each other wealth.)" },
{ word: "橘子", meaning: "orange; tangerine", example: "過年家裡一定會買很多橘子。(For New Year, our family always buys lots of tangerines.)" },
{ word: "更加", meaning: "even more", example: "聽完故事後，我更加了解春節的文化。(After hearing the story, I understand Spring Festival culture even more.)" },
{ word: "響", meaning: "to ring; to sound; to make a noise", example: "十二點一到，鞭炮就響了起來。(As soon as it struck midnight, the firecrackers started going off.)" },
{ word: "舅舅", meaning: "mother’s brother; uncle (on maternal side)", example: "寒假的時候，我去舅舅家玩。(During winter vacation, I go to my uncle’s house to play.)" },
{ word: "舅媽", meaning: "aunt (wife of mother’s brother", example: "舅媽做的菜很好吃。(The dishes my aunt makes are very delicious.)" },
{ word: "親切", meaning: "kind; friendly; warm (in manner)", example: "那位老師很親切，常常關心學生。(That teacher is very kind and often cares about the students.)" },
{ word: "相當", meaning: "quite; rather; fairly", example: "今天外面相當冷，出門要多穿一點。(It’s quite cold outside today; wear more if you go out.)" },
{ word: "溫暖", meaning: "warm; warmth (literal or emotional)", example: "家人的笑容讓我覺得很溫暖。(My family’s smiles make me feel very warm.)" },
{ word: "感謝", meaning: "to thank; to be grateful; gratitude", example: "謝謝你幫我，我真的很感謝你。(Thank you for helping me, I’m really grateful to you.)" },
{ word: "年夜飯", meaning: "reunion dinner on Chinese New Year’s Eve", example: "我們一家人一起吃年夜飯，聊一年的事情。(Our family eats New Year’s Eve dinner together and talks about the past year.)" },
{ word: "年糕", meaning: "glutinous rice cake", example: "過年的時候，奶奶會做甜年糕給我們吃。(During the New Year, Grandma makes sweet rice cakes for us to eat.)" },
{ word: "發糕", meaning: "sponge cake; prosperity steamed rice cake", example: "發糕的「發」有發財、變好的意思。(In prosperity cake, the word “fa” has the meaning of getting rich and things getting better.)" },
{ word: "蘿蔔糕", meaning: "radish cake", example: "很多人過年喜歡煎蘿蔔糕當早餐。(Many people like to pan-fry radish cake as breakfast during the New Year.)" },
{ word: "年年有餘", meaning: "to have surplus every year (New Year blessing)", example: "祝大家新的一年年年有餘。(I wish everyone surplus year after year in the new year.)" },
{ word: "年年高升", meaning: "to get promoted year by year", example: "老師祝同學們成績年年高升。(The teacher wishes the students’ grades to rise year after year.)" },
{ word: "平平安安", meaning: "to be safe and sound; peaceful and safe", example: "爸爸媽媽希望我們全家平平安安。(Mom and Dad hope our whole family will be safe and sound.)" },
{ word: "大吉大利", meaning: "to have great luck and great profit; lots of good fortune", example: "過年門口貼著「大吉大利」的春聯。(At New Year, a “great luck and great profit” couplet is pasted on the door.)" }
];
